services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - server
